# Generated by Django 6.0 on 2025-12-15 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('certified_preowned', 'Certified Pre-Owned'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], max_length=50)),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('truck', 'Truck'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('van', 'Van'), ('hatchback', 'Hatchback')], max_length=50)),
                ('exterior_color', models.CharField(blank=True, max_length=50)),
                ('interior_color', models.CharField(blank=True, max_length=50)),
                ('transmission', models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT')], max_length=50)),
                ('fuel_type', models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('plug_in_hybrid', 'Plug-in Hybrid')], max_length=50)),
                ('engine', models.CharField(blank=True, max_length=200)),
                ('drivetrain', models.CharField(blank=True, choices=[('fwd', 'FWD'), ('rwd', 'RWD'), ('awd', 'AWD'), ('4wd', '4WD')], max_length=20)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('primary_image', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('has_360_view', models.BooleanField(default=False)),
                ('dealer_name', models.CharField(blank=True, max_length=200)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=100)),
                ('location_zip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('quotes_count', models.IntegerField(default=0)),
                ('certification', models.CharField(blank=True, max_length=200)),
                ('warranty_info', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
