# Generated by Django 6.0 on 2025-12-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_add_phash_dedupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/%Y/%m/%d/'),
        ),
    ]
