# Generated by Django 6.0 on 2026-01-07 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0006_photo_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('vehicle_title', models.CharField(max_length=255)),
                ('vehicle_year', models.IntegerField()),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_vin', models.CharField(blank=True, max_length=50)),
                ('vehicle_mileage', models.IntegerField(blank=True, null=True)),
                ('vehicle_image_url', models.URLField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documentation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('buyer_zip', models.CharField(max_length=20)),
                ('buyer_city', models.CharField(blank=True, max_length=100)),
                ('buyer_state', models.CharField(blank=True, max_length=100)),
                ('financing_term', models.IntegerField(blank=True, help_text='Months', null=True)),
                ('financing_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financing_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('financing_down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dealer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='sales.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['user', 'status'], name='sales_quote_user_id_4e196b_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['reference_number'], name='sales_quote_referen_53282c_idx'),
        ),
    ]
